version: "3.9"
services:
  db_auth:
    container_name: db_auth
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_auth
      - PGDATA=/var/lib/postgresql/auth_data
    volumes:
      - ./db/shortcut/auth_data:/var/lib/postgresql/auth_data
    ports:
      - "5430:5432"
    restart: always
  mock_auth:
    container_name: mock_auth
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_auth:5432/cd_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_NOTIFICATION=http://notification:9920
    ports:
      - "9900:9900"
    depends_on:
      - db_auth
  db_desc:
    container_name: db_desc
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_desc
      - PGDATA=/var/lib/postgresql/desc_data
    volumes:
      - ./db/shortcut/desc_data:/var/lib/postgresql/desc_data
    ports:
        - "5429:5432"
    restart: always
  mock_desc:
    container_name: mock_desc
    build:
      context: ./services/desc
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_desc:5432/cd_desc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_NOTIFICATION=http://notification:9920
    ports:
      - "9902:9902"
    depends_on:
      - db_desc
  db_mock:
    container_name: db_mock
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mock
      - PGDATA=/var/lib/postgresql/mock_data
    volumes:
      - ./db/shortcut/mock_data:/var/lib/postgresql/mock_data
    ports:
      - "5428:5432"
    restart: always
  mock_mock:
    container_name: mock_mock
    build:
      context: ./services/mock
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_mock:5432/mock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_NOTIFICATION=http://localhost:9920
    ports:
      - "9912:9912"
    depends_on:
      - db_mock
  db_noti:
    container_name: db_noti
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_notification
      - PGDATA=/var/lib/postgresql/noti_data
    volumes:
      - ./db/shortcut/noti_data:/var/lib/postgresql/noti_data
    ports:
      - "5427:5432"
    restart: always
  mock_noti:
    container_name: mock_noti
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_noti:5432/cd_notification
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_AUTH=http://localhost:9900
      - SERVER_SITE_URL_LOGIN=http://mock_site:8081/login
    ports:
      - "9920:9920"
    depends_on:
      - db_noti
  mock_site:
    container_name: mock_site
    build:
      context: ./services/site
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SECURITY_OAUTH2_RESOURCE_USERINFOURI=http://auth:9900/user
      - SECURITY_OAUTH2_TOKENURI=http://auth:9900/oauth/token
      - SERVER_AUTH=http://auth:9900
      - SERVER_AUTH_PING=http://auth:9900/ping
      - SERVICE_MOCK=http://mock:9912
      - SERVICE_DESC=http://desc:9902
      - SERVICE_NOTIFICATION=http://notification:9920
    depends_on:
      - mock_auth
      - mock_desc
      - mock_mock
      - mock_noti