version: "3.9"
services:
  dbAuth:
    container_name: dbAuth
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_auth
      - PGDATA=/var/lib/postgresql/auth_data
    volumes:
      - ./db/shortcut/auth_data:/var/lib/postgresql/auth_data
    ports:
      - "5430:5432"
    restart: always
  auth:
    container_name: auth
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbAuth:5432/cd_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_NOTIFICATION=http://noti:9920
    ports:
      - "9900:9900"
    depends_on:
      - dbAuth
  dbDesc:
    container_name: dbDesc
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_desc
      - PGDATA=/var/lib/postgresql/desc_data
    volumes:
      - ./db/shortcut/desc_data:/var/lib/postgresql/desc_data
    ports:
        - "5429:5432"
    restart: always
  desc:
    container_name: desc
    build:
      context: ./services/desc
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbDesc:5432/cd_desc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_NOTIFICATION=http://noti:9920
    ports:
      - "9902:9902"
    depends_on:
      - dbDesc
  dbMock:
    container_name: dbMock
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mock
      - PGDATA=/var/lib/postgresql/mock_data
    volumes:
      - ./db/shortcut/mock_data:/var/lib/postgresql/mock_data
    ports:
      - "5428:5432"
    restart: always
  mock:
    container_name: mock
    build:
      context: ./services/mock
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbMock:5432/mock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_NOTIFICATION=http://noti:9920
    ports:
      - "9912:9912"
    depends_on:
      - dbMock
  dbNoti:
    container_name: dbNoti
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_notification
      - PGDATA=/var/lib/postgresql/noti_data
    volumes:
      - ./db/shortcut/noti_data:/var/lib/postgresql/noti_data
    ports:
      - "5427:5432"
    restart: always
  noti:
    container_name: noti
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbNoti:5432/cd_notification
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_AUTH=http://auth:9900
      - SERVER_SITE_URL_LOGIN=http://site:8081/login
    ports:
      - "9920:9920"
    depends_on:
      - dbNoti
  site:
    container_name: site
    build:
      context: ./services/site
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SECURITY_OAUTH2_RESOURCE_USERINFOURI=http://auth:9900/user
      - SECURITY_OAUTH2_TOKENURI=http://auth:9900/oauth/token
      - SERVER_AUTH_PING=http://auth:9900/ping
      - SERVICE_AUTH=http://auth:9900
      - SERVICE_MOCK=http://mock:9912
      - SERVICE_DESC=http://desc:9902
      - SERVICE_NOTIFICATION=http://noti:9920
    depends_on:
      - auth
      - desc
      - mock
      - noti